//1.db.Movie.find()
//2.db.Movie.find({},{name:1,year:1}).sort({year:-1,name:1})
//3.db.Movie.find({genre:{$in: ["romatic","drama"]}},{TenPhim:"$name",MoTa:"$description"})
//4.db.Movie.find({ $and: [{year:{$gte:2000}},{genre:{$eq:"romantic"}}]},{TenPhim:1, year:1})
//5.db.Movie.find({TenPhim: {$nin: ["Inception","Sunshine"]}},{TenPhim:1})
//6.db.Movie.find({description:{$in: [/Love/i]}},{name:1,year:1})
//7.db.Movie.find({description: {$exists: false}},{name:1,year:1}).skip(2)
//8.db.Movie.find({ratings: {$exists: false}},{name:1}).sort({name:1})
//9.db.Movie.find({"ratings.rating": {$gte: 3}},{name:1, year:1})